"""
Compute FP
"""

In [1]:
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem, Descriptors

In [2]:
# from rdkit.Chem.Draw import IPythonConsole
# from rdkit.Chem import Draw
# IPythonConsole.ipython_useSVG=True

In [10]:
import numpy as np
import pandas as pd

from compute_fp.com_fp_BV import morgan2, morgan3, maccskeys, atom, topological

In [11]:
root = {"root": "/home/barbara/Documents/DIFACQUIM/PPI_classifier/phase-1/Databases/",
        "root_Info" : "/home/barbara/Documents/DIFACQUIM/PPI_classifier/phase-1/Supervised_Models/SVM/Info",
        "root_ROC" : "/home/barbara/Documents/DIFACQUIM/PPI_classifier/phase-1/Supervised_Models/SVM/ROC"}

#### Reading molecules and activity from SDF

In [12]:
class CompFP:
    
    def __init__(self, input_file):
        self.Data  = pd.read_csv(str(root["root"]) + str(input_file))
        #Muestreo
        self.Data = pd.DataFrame.sample(self.Data, frac=0.01, replace=True,  random_state=1992, axis=None) 
        
    def fp_array(self, fp_func):
        smiles = self.Data.SMILES.to_list()
        fp = fp_func(smiles)
        output = []
        for f in fp:
            arr = np.zeros((1,))
            DataStructs.ConvertToNumpyArray(f, arr)
            output.append(arr)
        y = np.asarray(output)
        print(y.shape)
        print(y)
        return y

In [13]:
a = CompFP("BIOFACQUIM_DB.csv")

In [20]:
a.fp_array(morgan2)

(4, 2048)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [8]:
id = ['ID Database', 'Name', 'SMILES', 'subLibrary', 'Library', 'PPI', 'Epigenetic']